language: go

os:
  - osx

go:
  - 1.13.x
  - 1.14.x

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
  - "mkdir -p $GOPATH/github.com/lxc"
  - "rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/lxc/lxd/"

script:
  - "make client"
  - "go test ./client"
  - "go test ./lxc"
  - "go test ./shared"

notifications:
  webhooks: https://linuxcontainers.org/webhook-lxcbot/
