name: Commits
on:
  - pull_request

jobs:
  dco-check:
    name: Signed-off-by (DCO)
    runs-on: ubuntu-20.04
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check that all commits are signed-off
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}

  target-branch:
    name: Branch target
    runs-on: ubuntu-20.04
    steps:
    - name: Check branch target
      env:
        TARGET: ${{ github.event.pull_request.base.ref }}
      run: |
        set -x
        [ "${TARGET}" = "master" ] && exit 0

        echo "Invalid branch target: ${TARGET}"
        exit 1
