name: Triaging
on:
- pull_request_target

jobs:
  label:
    name: PR labels
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
